//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities : DbContext
    {
        public DbCvEntities()
            : base("name=DbCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLADMİN> TBLADMİN { get; set; }
        public virtual DbSet<TBLDENEYİMLERİM> TBLDENEYİMLERİM { get; set; }
        public virtual DbSet<TBLEGİTİMLERİM> TBLEGİTİMLERİM { get; set; }
        public virtual DbSet<TBLHAKKİMDA> TBLHAKKİMDA { get; set; }
        public virtual DbSet<TBLHOBİLERİM> TBLHOBİLERİM { get; set; }
        public virtual DbSet<TBLİLETİSİM> TBLİLETİSİM { get; set; }
        public virtual DbSet<TBLSERTİFİKALARIM> TBLSERTİFİKALARIM { get; set; }
        public virtual DbSet<TBLYETENEK> TBLYETENEK { get; set; }
        public virtual DbSet<TBLSOSYALMEDYA> TBLSOSYALMEDYA { get; set; }
    }
}
